name: 03 Basice Events Filters

on:
  # pull_request:
  #   types:
  #     - closed
  #     - opend
  #   types: [closed, reopened]
  push:
    # branches-ignore:
    #   - master
    #   - main
    # tags:
    #   - v2
    paths:
      - "routes/web.php"

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print HW
        run: echo "Hello World"
