name: 04 Basice Events External Trigger

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print HW
        run: echo "Hello World"
