name: 06 Basics Context

on: workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context data
        # run: echo ${{ github }}
        run: echo "${{ github.actor }}"
      - name: Print Context two
        # run: echo ${{ github.event_name }}
        run: echo ${{ job.status }}
      - name: Print JSON Context
        run: echo ${{ toJson(github)}}
