name: 07 Basics Conditions

on:
  pull_request:
    types:
      - closed

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World ^^"
      - name: Print GitHub Context
        run: echo ${{ toJson(github) }}
