name: 07 Basics Conditions

on:
  pull_request:
    types:
      - closed

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }} #job scope
    # if: github.event.pull_request.merged == true
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Print Conditional Message
        if: github.event.pull_request.changed_files > 1 # step scope
        run: echo "This Pull Request Has Multiple Changed Fiels"
