name: 08 Basics VAriables
run-name: ${{ github.actor }} Explaining Varibales - Try Number ${{ github.run_number }}

env: # workfolw scope
  # NAME: Value
  MY_NAME: "Mohamed Gheit"

on:
  workflow_dispatch

jobs:
  print-variables:
    runs-on: ubuntu-latest
    env: # job scope varibale
      MY_NAME2: "Mohamed Saad"
    steps:
      - name: Print Variables
        # run: echo $MY_NAME
        env: # step scope variable
          MY_AGE: "My age"
        run: echo ${{ env.MY_NAME }} and my age is ${{ env.My_AGE}}

      - name: Print job Scope
        run: echo ${{ env.MY_NAME2 }} and my age is ${{ env.My_AGE}} # age will be empty


  print-variables-second:
    runs-on: ubuntu-latest
    steps:
      - name: Print job Other Var
        run: echo ${{ env.MY_NAME2 }} # this won't work
