name: 08 Basics VAriables
run-name: ${{ github.actor }} Explaining Varibales - Try Number ${{ github.run_number }}

on:
  workflow_dispatch

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo "Hello World!"
