name: 14 Basics Matrix
run-name: ${{ github.actor }} Trying Matrix - Try Number ${{ github.run_number }}

on:
  workflow_dispatch

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix: # multi-dimension matrix
        os: [ubuntu-latest, windows-latest]
        php_version: [8.2, 8.3, 8.4]
        exclude:
          - os: ubuntu-latest
            php_version: 8.3
    steps:
      - name: Build Project
        run: echo "Build Project On Operating System ( ${{ matrix.os }} )  and php runs on ( ${{ matrix.php_version }} )"
