name: 16 Basics Marketpalece
run-name: ${{ github.actor }} Trying Marketpalece - Try Number ${{ github.run_number }}

on:
  workflow_dispatch

jobs:
  php-version:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup PHP Version 7.2
      #   # - uses: actions/checkout@v3
      #   uses: nanasess/setup-php@v4
      #   with:
      #     php-version: '7.2'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'


      - name: Check PHP php-version
        run: php -v
