name: 20 Basics Custom Actions
run-name: ${{ github.actor }} Trying Custom Actions - Try Number ${{ github.run_number }}

on:
  workflow_dispatch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Echo Hello World
        uses: ./.github/actions/print-hello-world
